### ISSUE TITLE
FastCDC Iterator size_hint

### ISSUE THREAD

**Issue by rickvanprim** [nlfiedler/fastcdc-rs#13]
It seems like it would be a small optimization to supply `Iterator::size_hint()` to cut down on allocations when using `collect()`.  Given the bounds on chunk sizes, it seems like this is straightforward to calculate, where size is `[source.len() / min_size, source.len() / max_size]`.

One other consideration, from my little bit of digging in to `Vec`'s `FromIter` and reading https://internals.rust-lang.org/t/is-size-hint-1-ever-used/8187/2, it doesn't seem like the upper bound is ever used, so my preference would be to "incorrectly" supply the upper bound as both the lower bound and upper bound and avoid the essentially guaranteed additional allocation if we start with the lower bound for capacity.

If this change seems reasonable, I'd be happy to make a PR 🙂

**Comment by nlfiedler** [comment]
Sounds like an excellent idea.

**Comment by rickvanprim** [comment]
Mind publishing a new version?

**Comment by nlfiedler** [comment]
New version is now published, hope it helps.
