### ISSUE TITLE
Provide hash in chunk struct

### ISSUE THREAD

**Issue by dristic** [nlfiedler/fastcdc-rs#15]
One limitation I'm running into is identifying chunks by a unique identifier without having to rehash the contents. I'm wondering if it would be useful to expose the hash value of the chunk in the `Chunk` struct? The `cut` function could potentially return `(u32, usize)` and then add that to the return of the iterator.

Thanks for the crate it works well!

**Comment by nlfiedler** [comment]
Sure, if that's useful. I welcome pull requests.
