### ISSUE TITLE
v2020 equivalent of FastCDC::with_eof

### ISSUE THREAD

**Issue by ariel-miculas** [nlfiedler/fastcdc-rs#22]
Need to figure out how to use [fastcdc](https://docs.rs/fastcdc/latest/fastcdc/index.html)::[v2020](https://docs.rs/fastcdc/latest/fastcdc/v2020/index.html)::[StreamCDC](https://docs.rs/fastcdc/latest/fastcdc/v2020/struct.StreamCDC.html#) in order to obtain the same effect as the ronomon's `FastCDC::with_eof`

My goal is to rewrite the current puzzlefs implementation (based on fastcdc 1.0.5) which uses a custom streaming implementation: https://github.com/anuvu/puzzlefs/blob/master/builder/src/fastcdc_fs.rs

It would also address https://github.com/anuvu/puzzlefs/issues/15

**Comment by nlfiedler** [comment]
My suggestion would be to copy the parts of the FastCDC implementation that you need, wrapping it in your own streaming logic. The actual code is extremely simple, just two tables of data and a single function (lines 35-285 of the v2020 code). You have my blessing to copy the code, it is merely a translation from other sources, after all.

While I don't entirely understand the problem you're solving, it may help to evaluate other research that considers the next one or two levels up the stack, such as described in QuickCDC, RapidCDC, and more recently, SuperCDC. These discuss how to apply data deduplication at a larger scale. As you noted, FastCDC is only suited to dealing with single files.

**Comment by ariel-miculas** [comment]
puzzlefs is a filesystem designed for container images. Basically, it traverses a root filesystem (represented by a directory) in a deterministic way, it concatenates all the files to form a stream of bytes and then it feeds this stream to FastCDC. In version 1.0.5 of this library, it used a custom streaming implementation with the help of FastCDC::with_eof (so it can signal that there will be more data to come).

> As you noted, FastCDC is only suited to dealing with single files.

Are you referring to `FastCDC` the library?

I managed to implement a solution using your StreamCDC, inspired by [chain](https://doc.rust-lang.org/std/io/trait.Read.html#method.chain). I've implemented `Read` for a custom structure which basically returns data from a list of files instead of a single file, you can see it [here](https://github.com/ariel-miculas/puzzlefs/blob/upgrade_fastcdc/builder/src/lib.rs#L55). It greatly simplifies the previous puzzlefs implementation based on the custom wrapper.
> such as described in QuickCDC, RapidCDC, and more recently, SuperCDC.

Thanks for the linked resources.

**Comment by nlfiedler** [comment]
FastCDC the algorithm is suited to processing a single file, although in your case it's a very long stream of bytes. The higher level approaches described in the papers for QuickCDC, RapidCDC, and SuperCDC all involve additional record keeping to improve chunking speed when processing many similar files repeatedly over time. They also leverage lower entropy checksums, typically the "hash" produced by the CDC algorithm, in an effort to improve throughput.

It seems like you have a solution now, so I'll close this issue. Feel free to ask questions or open new issues any time.

**Comment by ariel-miculas** [comment]
Thanks!
