### ISSUE TITLE
Extremely low MIN,AVG,MAX on v2020

### ISSUE THREAD

**Issue by ciehanski** [nlfiedler/fastcdc-rs#24]
Hello! Thank you for your effort in maintaining this crate!

I'm currently using the `ronomon` version of the FastCDC algorithm and have been looking to switch over to `v2020`. I am having issues since the consts max for MIN, AVERAGE, and MAX have been lowered significantly and the assertions confirming their sizes panic before I can recover: `panicked at 'assertion failed: avg_size <= AVERAGE_MAX'`

Here is the AVERAGE_MAX const per algorithm:

Ronomon: ```pub const AVERAGE_MAX: usize = 268_435_456;```
v2020:  ```pub const AVERAGE_MAX: u32 = 4_194_304;```

Any reason the average max only be set to 4 MB? Are these values set and specified in the whitepaper? It's quite limiting and the amount of chunks generated by one file would increase dramatically if I switch algorithms. 

Cheers,
ciehanski

**Comment by nlfiedler** [comment]
The reason for the chunk limits is that the v2016 and v2020 implementations are meant to conform to the algorithm and computed constants described in the original papers. Meanwhile, Greef made ronomon to work well with JavaScript, and made other adjustments as well. One of those was to drop the hard-coded bit masks developed by Xia, and as such the chunk size limits are much wider.

My suggestion would be to either continue using ronomon or fork whichever implementation you prefer and remove the limits, dropping the bit mask table and computing the masks using the simplistic method found in ronomon. The original paper's intent was for use in data deduplication in cloud storage, and in that setting, chunks are generally much smaller than 4mb. Your case may be quite different, so it makes sense to have an implementation specific to your needs.
