### ISSUE TITLE
Purpose of Box in StreamCDC struct

### ISSUE THREAD

**Issue by tazjin** [nlfiedler/fastcdc-rs#25]
Hey!

The `StreamCDC` struct currently contains a `Box<dyn Read>`, which requires an additional heap allocation and potentially prevents some compiler optimisations by obscuring the reader type.

Is there a particular reason for this Box that isn't immediately obvious, or would you accept a change to parameterise StreamCDC over an `R: Read`, such that monomorphisation can occur?

Thanks for this crate! :)

**Comment by nlfiedler** [comment]
It was that way because I didn't know any better. In an effort to learn Rust more thoroughly I went ahead and made the change. Thank you for pointing it out, and offering to fix it.

**Comment by tazjin** [comment]
Great, thank you! :)
