### ISSUE TITLE
v2020 version is not 30-40% better than v2016 version?

### ISSUE THREAD

**Issue by bduffany** [nlfiedler/fastcdc-rs#27]
In my benchmarks, I have not been able to reproduce the experimental result in the paper that the "rolling two bytes each time" optimization improves performance by 30-40%.

One benchmark is to use the example in this repo:

```
hyperfine \
  --warmup 2 \
  --parameter-list version v2016,v2020 \
  'cargo run --example {version} -- --size 16384 test/fixtures/SekienAkashita.jpg'
```

`hyperfine` reports ~50ms duration on my machine for both versions, with 1.00 +/- 0.02x performance difference.

I also ran a different benchmark on one of my own datasets, with 2 GB of cache artifacts generated by a `bazel build`. In my experimental setup I was using 8 threads, and using fastcdc-rs (comparing v2016 vs v2020) to chunk all 2GB of files in parallel (just reading the files and chunking them, and throwing away the result - nothing else).

With 8 threads enabled I found that v2020 was only 1.01X faster than v2016. With 1 thread enabled I see that v2020 is 1.07X faster. Two observations about these results:
* The best case (7% faster single-threaded performance) is much less than 30-40%
* Multi-threaded performance (in which I saw only 1% improvement) is probably more relevant for a real-world data deduplication system

Maybe the README could mention this data point as a caveat, to help manage expectations? Something like "the authors claim a 30-40% performance improvement, but one benchmark using this rust implementation showed a more modest improvement (roughly a 1% improvement for multi-threaded chunking, or a 7% improvement for single-threaded chunking)."

Here is my benchmark as a [gist](https://gist.github.com/bduffany/f407a7e076d3c573ed8106662cc70638) in case anyone would like to test with their dataset. Copy it to `src/main.rs` in a clone of this repo, then run it like `cargo add walkdir crossbeam-channel && cargo build && hyperfine --warmup 2 --parameter-list version 2016,2020 './target/release/fastcdc DATA_DIR'` -- replace DATA_DIR with your custom data directory, preferably with many files exceeding the min chunk size.

**Comment by nlfiedler** [comment]
Which CPU architecture were the benchmarks running on? That probably makes a difference. The paper has some discussion about the number of instructions and such, so they may have been testing with systems that yielded the results they claimed. I'll also run some tests again. As I recall, when I tested with a 7gb file it was around 20% faster (on an ARM64 system).

**Comment by nlfiedler** [comment]
Did more testing and yep, the results are about 20% faster. The results may depend on the size of the input file and the size of the chunks. I was using larger files and larger chunks. I've updated the comment in the code to give some warning.

**Comment by bduffany** [comment]
Ah. I was not using `mmap` in my benchmark - the fact that my benchmark is calling read() likely dilutes things a bit, since I'm now seeing a 10-12% speedup for a 2.5 GB file if I switch to mmap. I see from your comment you tested with an M1 processor, I guess maybe that might be accounting for the remaining difference between our results (or maybe I need a 7GB file to test with). I'm on Linux, x86_64 (Intel i7-9700K)
