### ISSUE TITLE
Req: supply consume the byte as stream to avoid big buf as input

### ISSUE THREAD

**Issue by maobaolong** [nlfiedler/fastcdc-rs#3]
# background

We need to chunking the file from oss on cloud, and the file maybe big, and the chunking server may not have enough memory to hold in the chunk process, so we want to chunking the oss input stream which opened by chunking process, the chunking process use fastcdc-rs as a lib to cutting stream into chunk, but the chunking logic is in the fastcdc-rs lib.

# request

- If fastcdc-rs supply a way to consume the byte as stream, we can avoid big buf
- Supply to use this lib through jni or jnr to let java use this useful lib

**Comment by Smoozilla** [comment]
I am not sure this will/should be pulled into this repo but I have added some of the features from the project this was based on to allow streamed chunking.

https://github.com/Smoozilla/fastcdc-rs

for an example how it's used please see:

https://github.com/Smoozilla/fastcdc-wasm/blob/master/src/lib.rs

as well as the demo from project this repo was based on:

https://github.com/ronomon/deduplication/blob/master/demo.js

**Comment by ciehanski** [comment]
@Smoozilla, one question: why not use a bool for `flags` since its values can either be 1 or 0?

**Comment by Smoozilla** [comment]
Hi @ciehanski 

Didn't consider it, I just copied the original repo this was derived from. Probably could do with an update.

**Comment by nlfiedler** [comment]
@Smoozilla I like it, please submit a PR. The one thing I would want to change is to keep the old constructor for backward compatibility, and add the new "flags" constructor with a name like `with_flags()` or something to that effect.

**Comment by nlfiedler** [comment]
Okay, I have added a test after merging Bill's PR; the results are not what I expected. @Smoozilla when you have a chance, please review the test I added in commit 3d195a5 and see if I did something wrong. Thanks.

**Comment by Smoozilla** [comment]
@nlfiedler I can't speak for why mid chunks are not same length but last call missing a block should pass eof as true vs false

**Comment by nlfiedler** [comment]
Ugh, so stupid. Thanks, the test is fixed now.

**Comment by Smoozilla** [comment]
Glad to hear it worked, thanks a bunch for converting this to rust. I'm new with rust but quickly falling in love and can use this anywhere thanks to wasm and how versatile rust can be

**Comment by Smoozilla** [comment]
@nlfiedler I thought of something else. If you look here:

https://github.com/Smoozilla/fastcdc-wasm/blob/master/src/lib.rs

The bytes processed are kept track of, meaning the byte steam is moved forward only as many bytes as were actually processed. This could account for mid chunks having off boundaries.

**Comment by Smoozilla** [comment]
22366 + 8282 = 30648

so next call would be for example:

        let chunker = FastCDC::with_eof(&contents[30648..(30648 + buffer.len())], 8192, 16384, 32768, false);

and end at 30648 + size of buffer you're streaming through

**Comment by Smoozilla** [comment]
@nlfiedler I have submitted another pull request with the stream test modified and matching non-stream

**Comment by nlfiedler** [comment]
This is fixed, thanks to @Smoozilla
