### ISSUE TITLE
Test, example, API docs for AsyncStreamCDC

### ISSUE THREAD

**Issue by nlfiedler** [nlfiedler/fastcdc-rs#31]
The newly introduced `AsyncStreamCDC` needs unit tests, API documentation, and a working example. The first question is how to supply an appropriate `AsyncRead` to the chunker since tokio is not compatible.

**Comment by cdata** [comment]
Heya, I just noticed this ready-to-go `AsyncStreamCDC` implementation, but it's not in a release yet. Maybe I can help move it forward?

One observation I have is that there is a compatibility shim available for `AsyncRead` that covers both Tokio and Futures: https://crates.io/crates/async-compat

A separate but related observation is that Tokio implementations are trending in popularity, so it may make for a better default choice compared to Futures.

I would be willing to take a stab at writing some tests and documentation if you would consider compatibility via `async-compat` to be a suitable solution to the presented problem.

**Comment by nlfiedler** [comment]
Using `async-compat` seems to be a reasonable approach, I would welcome your help on this. Thanks.

**Comment by cdata** [comment]
I took a stab at it. I endedup including support for both `tokio` and `futures`, although `tokio` is the "default." It may be preferable to have no default at all and have async stream support be opt-in.

**Comment by nlfiedler** [comment]
I agree that pulling in other dependencies should be opt-in since this crate is still pretty small.

**Comment by cdata** [comment]
I updated the change to fix the doc example and also make async streaming opt-in.
