### ISSUE TITLE
Version 3.1.0 breaks semver

### ISSUE THREAD

**Issue by ariel-miculas** [nlfiedler/fastcdc-rs#34]
I have the following error when building:
```
error[E0107]: missing generics for struct `fastcdc::v2020::StreamCDC`
   --> puzzlefs-lib/src/builder.rs:111:18
    |
111 |     mut chunker: StreamCDC,
    |                  ^^^^^^^^^ expected 1 generic argument
```
Semver link: https://semver.org/#summary

**Comment by nlfiedler** [comment]
That is unfortunate, since that happened in 3.0.2 and we are currently at 3.1.0. If I reverse that change now and publish as 3.1.1, then it would break anyone that had already fixed their usage. Right? I'm open to suggestions as to how to fix this without causing more problems.

**Comment by ariel-miculas** [comment]
Yeah, I guess 3.0.2 should have been 4.0.0. I don't have a solution for this either, it's just something to be aware of for future versions.

**Comment by nlfiedler** [comment]
I have updated the CHANGELOG and the note on the 3.0.2 release so at least the issue will be easier to recognize ahead of time.
