### ISSUE TITLE
Hash Collisions

### ISSUE THREAD

**Issue by ilinchunjie** [nlfiedler/fastcdc-rs#37]
In testing, we've observed that some chunks experience hash collisions. Is there any way to avoid this?

**Comment by ilinchunjie** [comment]
[597299387647455390.zip](https://github.com/nlfiedler/fastcdc-rs/files/13376279/597299387647455390.zip)

**Comment by ilinchunjie** [comment]
I have uploaded two sample files that will result in hash collisions for testing purposes

**Comment by nlfiedler** [comment]
The hash generated by the algorithm has very low entropy, so collisions are to be expected. Other algorithms, such as SuperCDC, will make use of these hash values but combine them with additional information to take collisions into account. My recommendation is to simply ignore these hash values and use a better digest algorithm such as SHA2 or BLAKE3 for detecting duplicates and/or content-based addressing.

**Comment by ilinchunjie** [comment]
> The hash generated by the algorithm has very low entropy, so collisions are to be expected. Other algorithms, such as SuperCDC, will make use of these hash values but combine them with additional information to take collisions into account. My recommendation is to simply ignore these hash values and use a better digest algorithm such as SHA2 or BLAKE3 for detecting duplicates and/or content-based addressing.该算法生成的散列具有非常低的熵，因此冲突是可以预料的。其他算法（例如 SuperCDC）将利用这些哈希值，但将它们与附加信息结合起来以考虑冲突。我的建议是简单地忽略这些哈希值并使用更好的摘要算法（例如 SHA2 或 BLAKE3）来检测重复项和/或基于内容的寻址。

Thank you for your advice. We have now implemented an additional hash calculation on the chunked data using the xxhash algorithm.
